// CpSvrTools.idl : IDL-Quellcode für CpSvrTools.dll
//

// Diese Datei wird mit dem MIDL-Tool bearbeitet,
// um den Quellcode für die Typbibliothek (CpSvrTools.tlb)und die Abruffunktionen zu erzeugen.

import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(766287F3-9000-11d5-A550-0008C779C600),
		dual,
		helpstring("ICpLayout Interface"),
		pointer_default(unique)
	]
	interface ICpLayout : IDispatch
	{
		//Standard Server-seitige Komponenten Methoden
		HRESULT OnStartPage([in] IUnknown* piUnk);
		HRESULT OnEndPage();
		[id(1), helpstring("Methode Save")] HRESULT Save([in, string] BSTR bstrName, [in, string] BSTR bstrData);
		[id(2), helpstring("Methode Read")] HRESULT Read([in, string] BSTR bstrName, [out, string, retval] BSTR *pbstrData);
		[id(3), helpstring("Methode Init")] HRESULT Init([in, string] BSTR bstrPath, [in, string] BSTR bstrUser);
		[id(4), helpstring("Methode GetDefaultName")] HRESULT GetDefaultName([out, string, retval] BSTR *pbstrName);
		[id(5), helpstring("Methode SetDefaultName")] HRESULT SetDefaultName(BSTR bstrName);
		[id(6), helpstring("Methode GetNameList")] HRESULT GetNameList([out, string, retval] BSTR* pbstrList);
		[id(7), helpstring("Methode Delete")] HRESULT Delete([in, string] BSTR bstrName);			
	};
[
 
	uuid(766287F1-9000-11d5-A550-0008C779C600),
	version(1.0),
	helpstring("4C_20_CP.CpSvrTools 1.0 Typbibliothek")
]
library CPSVRTOOLSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(766287F2-9000-11d5-A550-0008C779C600),
		helpstring("CpLayout Class")
	]
	coclass CpLayout
	{
		[default] interface ICpLayout;
	};
};
