//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GrEditor.rc
//
#define IDR_GR_TYPE_SRVR_IP             4000
#define IDR_GR_TYPE_SRVR_EMB            4001
#define IDP_GR_OLE_INIT_FAILED          4002
#define ID_GR_POPUP_MENU                4004
#define IDR_GR_MAINFRAME                4020
#define IDR_GR_TOOLBAR_SFC              4021
#define IDR_GR_TOOLBAR_FBD              4022
#define IDR_GR_TOOLBAR_LD               4023
#define IDR_GR_TYPE                     4024
#define IDD_GR_ABOUTBOX                 4025
#define IDD_GR_ZOOM                     4026
#define IDD_GR_GRID                     4027
#define IDD_GR_PROP_CON                 4028
#define IDD_GR_PROP_LAB                 4029
#define IDD_GR_PROP_VAR                 4030
#define IDD_GR_PROP_CMT                 4031
#define IDD_GR_PROP_STEP                4032
#define IDD_GR_PROP_TRAN                4033
#define IDD_GR_PROP_DIV                 4034
#define IDD_GR_PROP_ACT                 4035
#define IDD_GR_PROP_FB                  4036
#define IDD_GR_EDITVARIABLE             4037
#define IDC_GR_INSCOL                   4038
#define IDD_GR_PROP_ACT_V120            4039
#define IDD_GR_PROP_ACTBLK_V120         4039
#define IDD_GR_PROP_ACTBLK              4040
#define IDD_GR_PROP_CONTACT             4041
#define IDD_GR_STATISTIC                4043
#define IDC_GR_INSCOL1                  4050
#define IDC_GR_INSROW                   4051
#define IDC_GR_INSROW1                  4052
#define IDC_GR_DELCOL                   4053
#define IDC_GR_DELCOL1                  4054
#define IDC_GR_DELROW                   4055
#define IDC_GR_DELROW1                  4056
#define IDB_GR_CON_PREV01               4057
#define IDB_GR_CON_PREV02               4058
#define IDB_GR_LAB_PREV01               4059
#define IDB_GR_LAB_PREV02               4060
#define IDB_GR_VAR_PREV01               4061
#define IDB_GR_VAR_PREV02               4062
#define IDB_GR_VAR_PREV03               4063
#define IDB_GR_ICONCMT                  4064
#define IDB_GR_ICONVARRD                4065
#define IDB_GR_ICONLAB                  4066
#define IDB_GR_ICONLABR                 4067
#define IDB_GR_ICONRETL                 4068
#define IDB_GR_ICONRETR                 4069
#define IDB_GR_ICONCONR                 4070
#define IDB_GR_ICONCONL                 4071
#define IDB_GR_ICONCONLP                4072
#define IDB_GR_ICONCONRP                4073
#define IDB_GR_ICONVARWR                4074
#define IDB_GR_ICONVARFB                4075
#define IDC_GR_PENCUR                   4076
#define IDC_GR_PENCUR1                  4077
#define IDC_GR_VARVALUE                 4078
#define IDC_GR_VARNAME                  4079
#define IDC_GR_APPLY                    4080
#define IDB_GR_CT_PREV01                4086
#define IDB_GR_CT_PREV02                4087
#define IDB_GR_CT_PREV03                4088
#define IDB_GR_CT_PREV04                4089
#define IDB_GR_CL_PREV01                4090
#define IDB_GR_CL_PREV02                4091
#define IDB_GR_CL_PREV03                4092
#define IDB_GR_CL_PREV03a               4092
#define IDB_GR_CL_PREV04                4093
#define IDB_GR_CL_PREV05                4094
#define IDB_GR_CL_PREV06                4095
#define IDD_GR_PROP_COIL                4096
#define IDD_GR_PROP_LINE                4097
#define IDD_GR_PROP_PRAIL               4098
#define IDC_SECEDITCTRL                 4099
#define IDC_GR_ZOOM_400                 4100
#define IDC_GR_ZOOM_200                 4101
#define IDC_GR_ZOOM_100                 4102
#define IDC_GR_ZOOM_050                 4103
#define IDC_GR_ZOOM_CUSTOM              4104
#define IDC_GR_ZOOM_VALUE               4105
#define IDC_GR_GRID_NO                  4106
#define IDC_GR_GRID_POINT               4107
#define IDC_GR_GRID_CROSS               4108
#define IDC_GR_GRID_LINES               4109
#define IDC_GR_FB_NAME                  4110
#define IDC_GR_CON_NAME                 4111
#define IDC_GR_CON_PREV                 4112
#define IDC_GR_LAB_NAME                 4113
#define IDC_GR_LAB_PREV                 4114
#define IDC_GR_LAB_SRC                  4115
#define IDC_GR_LAB_DEST                 4116
#define IDC_GR_LAB_LINE                 4117
#define IDC_GR_VAR_NAME                 4118
#define IDC_GR_VAR_TYPE                 4119
#define IDC_GR_VAR_PREV                 4120
#define IDC_GR_CMT_TEXT                 4121
#define IDC_GR_CON_LEFT                 4122
#define IDC_GR_CON_RIGHT                4123
#define IDC_GR_STEP_NAME                4124
#define IDC_GR_STEP_INITIAL             4125
#define IDC_GR_TRAN_NAME                4126
#define IDC_GR_DIV_TYPE                 4127
#define IDC_GR_DIV_SIM                  4128
#define IDC_GR_DIV_ALT                  4129
#define IDC_GR_ACT_NAME                 4130
#define IDC_GR_ACT_QUAL                 4131
#define IDC_GR_ACT_TIME                 4132
#define IDC_GR_ACT_TIME2                4133
#define IDC_GR_ACT_STACTION             4134
#define IDC_GR_ACT_WARN                 4135
#define IDC_GR_STAT_FB                  4136
#define IDC_GR_STAT_FCT                 4137
#define IDC_GR_STAT_PRO                 4138
#define IDC_GR_STAT_VARRD               4139
#define IDC_GR_STAT_VARWR               4140
#define IDC_GR_STAT_VARFB               4141
#define IDC_GR_STAT_LABEL               4142
#define IDC_GR_STAT_JUMP                4143
#define IDC_GR_STAT_RET                 4144
#define IDC_GR_STAT_CONT                4145
#define IDC_GR_STAT_CONN                4146
#define IDC_GR_STAT_CMT                 4147
#define IDC_GR_STAT_STEP                4148
#define IDC_GR_STAT_TRA                 4149
#define IDC_GR_STAT_ACTION              4150
#define IDC_GR_STAT_SUMFBD              4151
#define IDC_GR_STAT_SUMSFC              4152
#define IDC_GR_STAT_ACTBLK              4153
#define IDC_GR_STAT_ALTDIV              4154
#define IDC_GR_STAT_SIMDIV              4155
#define IDC_GR_STAT_SUMLINES            4156
#define IDC_GR_STAT_FIXLINE             4157
#define IDC_GR_STAT_POWERRAIL           4158
#define IDC_GR_STAT_CONTACT             4159
#define IDC_GR_STAT_RUBBLINE            4160
#define IDC_GR_STAT_TOTAL               4161
#define IDC_GR_STAT_COIL                4162
#define IDC_GR_STAT_SUMLD               4163
#define IDC_GR_CT_NAME                  4170
#define IDC_GR_CT_TYPE                  4171
#define IDC_GR_CT_PREV                  4172
#define IDC_GR_CL_NAME                  4173
#define IDC_GR_CL_TYPE                  4174
#define IDC_GR_CL_PREV                  4175
#define IDC_GR_VERSIONINFO              4176
#define IDC_GR_DEFAULT_SIZE             4181
#define IDC_GR_ACT_LDACTION             4183
#define IDC_GR_ACT_FBDACTION            4184
#define ID_GR_STATISTIC                 4399
#define ID_GR_SEL_ALL                   4400
#define ID_GR_CANCEL_EDIT_SRVR          4401
#define ID_GR_VIEW_TOOLBAR_SFC          4402
#define ID_GR_VIEW_TOOLBAR_FBD          4403
#define ID_GR_VIEW_TOOLBAR_LD           4404
#define ID_GR_VIEW_ZOOM                 4405
#define ID_GR_VIEW_ZOOMIN               4406
#define ID_GR_VIEW_ZOOMOUT              4407
#define ID_GR_VIEW_GRID                 4408
#define ID_GR_INS_FB                    4409
#define ID_GR_INS_LAB                   4410
#define ID_GR_INS_CMT                   4411
#define ID_GR_INS_RET                   4412
#define ID_GR_INS_STEP                  4413
#define ID_GR_INS_TRANSITION            4414
#define ID_GR_INS_ACTION                4415
#define ID_GR_INS_DIVCON                4416
#define ID_GR_INS_SDIVCON               4417
#define ID_GR_INS_VAROUT                4418
#define ID_GR_INS_VARIN                 4419
#define ID_GR_INS_JMP                   4420
#define ID_GR_INS_CONIN                 4421
#define ID_GR_INS_CONOUT                4422
#define ID_GR_INS_ACTIONBLOCK           4423
#define ID_GR_INS_VARINOUT              4424
#define ID_GR_EDIT_RESIZE               4425
#define ID_GR_EDIT_LINE                 4426
#define ID_GR_EDIT_COMMENT              4427
#define ID_GR_EDIT_UNCOMMENT            4428
#define ID_GR_EDIT_NAME                 4429
#define ID_GR_EDIT_PROPERTY             4430
#define ID_GR_EDIT_ROW                  4431
#define ID_GR_EDIT_COL                  4432
#define ID_GR_empty0                    4433
#define ID_GR_OPT_LINERUBB              4448
#define ID_GR_OPT_COLNORMAL             4449
#define ID_GR_OPT_COLSELECT             4450
#define ID_GR_OPT_COLERROR              4451
#define ID_GR_OPT_COLCOMMENT            4452
#define ID_GR_OPT_COLRUBBER             4453
#define ID_GR_OPT_COLEDITLINE           4454
#define ID_GR_OPT_COLGRID               4455
#define ID_GR_OPT_COLBACKGD             4456
#define ID_GR_OPT_COLELEMBK             4457
#define ID_GR_OPT_COLFBLKBK             4458
#define ID_GR_OPT_COLLADDBK             4459
#define ID_GR_OPT_COLEDGE               4460
#define ID_GR_OPT_COLLIGHTPIN           4461
#define ID_GR_OPT_COLBRKREC             4462
#define ID_GR_OPT_COLBRKDIS             4463
#define ID_GR_OPT_COLBRKACT             4464
#define ID_GR_OPT_COLBRKDEC             4465
#define ID_GR_OPT_COLUNUSED             4466
#define ID_GR_OPT_COLBACKGD_SFC         4467
#define ID_GR_OPT_COLELEMBK_SFC         4468
#define ID_GR_OPT_COLLADDBK_SFC         4469
#define ID_GR_OPT_COLFBLKBK_SFC         4470
#define ID_GR_OPT_COLACTIVE_SFC         4471
#define ID_GR_OPT_COLFORCED_SFC         4472
#define ID_GR_OPT_COLBLOCKD_SFC         4473
#define ID_GR_OPT_FONT                  4474
#define ID_GR_OPT_RECON                 4480
#define ID_GR_OPT_SFC                   4481
#define ID_GR_DEBUG                     4482
#define ID_GR_DEBUG2                    4483
#define ID_GR_STEP_TOGGLEINIT           4484
#define ID_GR_EDIT_INSTAMCE             4485
#define ID_GR_EDIT_ACT_NONE             4486
#define ID_GR_EDIT_ACT_N                4487
#define ID_GR_EDIT_ACT_R                4488
#define ID_GR_EDIT_ACT_S                4489
#define ID_GR_EDIT_ACT_L                4490
#define ID_GR_EDIT_ACT_D                4491
#define ID_GR_EDIT_ACT_P                4492
#define ID_GR_EDIT_ACT_SD               4493
#define ID_GR_EDIT_ACT_DS               4494
#define ID_GR_EDIT_ACT_SL               4495
#define ID_GR_EDIT_ACT_P0               4496
#define ID_GR_EDIT_ACT_P1               4497
#define ID_GR_INS_FB_CALL               4498
#define ID_GR_VIEW_OBJHELP              4499
#define ID_GR_CONTINUE_TASK             4500
#define ID_GR_STEP_INTO                 4501
#define ID_GR_SET_WATCHPOINT            4502
#define ID_GR_CLEAR_WATCHPOINT          4503
#define ID_GR_CLEAR_ALL_WATCHPOINTS     4504
#define ID_GR_REMOVE_ALL_BREAKPOINTS    4505
#define ID_GR_TOGGLE_BREAKPOINT         4506
#define ID_GR_TOGGLE_BREAKPOINT_ENABLED 4507
#define ID_GR_EN_PROPEDIT               4508
#define ID_GR_ROUTE                     4509
#define ID_GR_UNROUTE                   4510
#define ID_GR_WRITE_WATCHPOINT          4511
#define ID_GR_TOGGLE_MANUAL_MODE        4512
#define ID_GR_PERFORM_CYCLE             4513
#define ID_GR_FORCE_TRANSITION_ONCE     4514
#define ID_GR_FORCE_TRANSITION          4515
#define ID_GR_BLOCK_TRANSITION          4516
#define ID_GR_FORCE_ALL_TRANSITIONS     4517
#define ID_GR_BLOCK_ALL_TRANSITIONS     4518
#define ID_GR_REVERT_ALL_TRANSITIONS    4519
#define ID_GR_GLOBALLY_FORCE_ALL_TRANSITIONS 4520
#define ID_GR_FORCE_ACTION_ONCE         4521
#define ID_GR_FORCE_ACTION              4522
#define ID_GR_BLOCK_ACTION              4523
#define ID_GR_BLOCK_ALL_ACTIONS         4524
#define ID_GR_FORCE_ALL_ACTIONS         4525
#define ID_GR_REVERT_ALL_ACTIONS        4526
#define ID_GR_GLOBALLY_BLOCK_ALL_ACTIONS 4527
#define ID_GR_CONTEXT_MENU              4528
#define ID_GR_EDIT_AUTOSIZE             4529
#define ID_GR_INS_POWER                 4530
#define ID_GR_INS_CT_NORMAL             4531
#define ID_GR_INS_CT_CLOSED             4532
#define ID_GR_INS_CT_POSTRANS           4533
#define ID_GR_INS_CT_NEGTRANS           4534
#define ID_GR_INS_CL_NORMAL             4535
#define ID_GR_INS_CL_NEGATIVE           4536
#define ID_GR_INS_CL_SET                4537
#define ID_GR_INS_CL_RESET              4538
#define ID_GR_INS_CL_POSTRANS           4539
#define ID_GR_INS_CL_NEGTRANS           4540
#define ID_GR_OPT_STDSIZE               4541
#define ID_GR_INS_HLINE                 4542
#define ID_GR_INS_VLINE                 4543
#define ID_GR_OPT_CHANGEWARN            4544
#define ID_GR_EDIT_PROP_STACTION        4545
#define ID_GR_EDIT_PROP_LDACTION        4546
#define ID_GR_EDIT_PROP_FBDACTION       4547
#define ID_GR_SHOW_VAR_SEL_POPUP        4549
#define ID_GR_XREF_LAST                 4551
#define ID_GR_XREF_NEXT                 4552
#define ID_GR_XREF_QUERY                4553
#define ID_GR_SHOW_VAR_SELECTION        4554
#define ID_GR_INS_EXCEPTION_ACTION      4555
#define ID_GR_INSERT_LRU_FIRST          4556
#define ID_GR_INSERT_LRU_LAST           4576
#define ID_GR_STEP_OVER                 4577
#define ID_GR_STEP_OUT                  4578
#define IDS_GR_EDIT_DEL                 4600
#define IDS_GR_EDIT_DELSEL              4601
#define IDS_GR_EDIT_DELLINE             4602
#define IDS_GR_EDIT_DELSIGNAL           4603
#define IDS_GR_CANNOT_CONTINUE_TASK     4604
#define IDS_GR_CANNOT_STEP_INTO         4605
#define IDS_GR_PRINTHEADER              4606
#define IDS_GR_PRINTFOOTER              4607
#define IDS_GR_NOIECIDENT               4608
#define IDS_GR_NAMEMASK_CON             4609
#define IDS_GR_NAMEMASK_LAB             4610
#define IDS_GR_NAMEMASK_VAR             4611
#define IDS_GR_NAMEMASK_STEP            4612
#define IDS_GR_NAMEMASK_TRAN            4613
#define IDS_GR_NAMEMASK_ACT             4614
#define IDS_GR_NAMEMASK_CONTACT         4615
#define IDS_GR_NAMEMASK_COIL            4616
#define IDS_GR_ERR_INVALID_POS          4617
#define IDS_GR_NAMEMASK_FB              4618
#define IDS_GR_CLIPTOOBIG               4619
#define IDS_GR_FINDNOWORDS              4620
#define IDS_GR_FINDNOREGEXP             4621
#define IDS_GR_CANNOT_PERFORM_CYCLE     4622
#define IDS_GR_CANNOT_FORCE_TRANSITION  4623
#define IDS_GR_CANNOT_BLOCK_TRANSITION  4624
#define IDS_GR_CANNOT_FORCE_TRANSITIONS 4625
#define IDS_GR_CANNOT_FORCE_ACTION      4626
#define IDS_GR_CANNOT_BLOCK_ACTION      4627
#define IDS_GR_CANNOT_BLOCK_ACTIONS     4628
#define IDS_GR_READONLY_WARNING         4629
#define IDS_GR_CANNOT_SET_MANUAL_MODE   4630
#define IDS_GR_CANNOT_RESET_MANUAL_MODE 4631
#define IDS_GR_CANNOT_WRITE_VAR         4633
#define IDS_GR_MSGBOX_TITLE             4634
#define IDS_GR_REG_SECTION              4635
#define IDS_GR_REG_RUBBLINE             4636
#define IDS_GR_REG_ZOOMVALUE            4637
#define IDS_GR_REG_RUBB_RECON           4638
#define IDS_GR_STACTION_WARN            4639
#define IDS_GR_EDIT_NOTFOUND            4640
#define IDS_GR_ERR_OVERLAP              4641
#define IDS_GR_ON_UPDATE_POSITION       4642
#define IDS_GR_REG_STEPSIZE             4643
#define IDS_GR_CTSIZE                   4645
#define IDS_GR_REG_TRANSIZE             4646
#define IDS_GR_REG_CTSIZE               4647
#define IDS_GR_REG_CLSIZE               4648
#define IDS_GR_REG_ACTSIZE              4649
#define IDS_GR_REG_ACTBLKSIZE           4650
#define IDS_GR_REG_VARSIZE              4653
#define IDS_GR_REG_LINESIZE             4655
#define IDS_GR_REG_PRAILSIZE            4656
#define IDS_GR_REG_AUTOSIZE             4657
#define IDS_GR_REG_CHANGEWARN           4658
#define IDS_GR_CHANGE_WARNING           4659
#define IDS_GR_REG_FBLKSIZE             4660
#define IDS_GR_REG_FUN_SIZE             4661
#define IDS_GR_REG_PRC_SIZE             4662
#define IDS_GR_WRONG_VAR_SYNTAX         4663
#define IDS_GR_WRONG_VALUE_SYNTAX       4664
#define IDS_GR_NO_TIME_QUALIFIER        4665
#define IDS_GR_FAILED_TO_WRITE_VAR      4666
#define IDS_GR_SFC_ACTION_TEXT_BLOCKED  4667
#define IDS_GR_SFC_ACTION_TEXT_FORCED   4668
#define IDS_GR_SFC_ACTION_TEXT_FORCED_PERMANENTLY 4669
#define IDS_GR_CONMENU_EDIT_CUT         4670
#define IDS_GR_CONMENU_EDIT_COPY        4671
#define IDS_GR_CONMENU_EDIT_PASTE       4672
#define IDS_GR_CONMENU_EDIT_CLEAR       4673
#define IDS_GR_CONMENU_INSERT_FB_CALL   4674
#define IDS_GR_CONMENU_INSERT_LRU_FIRST 4675
#define IDS_GR_CONMENU_SHOW_VAR_SELECTION 4676
#define IDS_GR_CONMENU_SHOW_VAR_SEL_POPUP 4677
#define IDS_GR_CONMENU_XREF_QUERY       4678
#define IDS_GR_CONMENU_XREF_LAST        4679
#define IDS_GR_CONMENU_XREF_NEXT        4680
#define IDS_GR_CONMENU_INSERT_VAR       4681
#define IDS_GR_CONMENU_INSERT_CONST     4682
#define IDS_GR_CONMENU_INSERT_VAR_GLOBAL 4683
#define IDS_GR_CONMENU_INSERT_VAR_EXTERNAL 4684
#define IDS_GR_CONMENU_INSERT_ASSIGNMENT 4685
#define IDS_GR_CONMENU_INSERT_IF        4686
#define IDS_GR_CONMENU_INSERT_CASE      4687
#define IDS_GR_CONMENU_INSERT_FOR       4688
#define IDS_GR_CONMENU_INSERT_WHILE     4689
#define IDS_GR_CONMENU_INSERT_REPEAT    4690
#define IDS_GR_CONMENU_INSERT_RETURN    4691
#define IDS_GR_CONMENU_INSERT_EXIT      4692
#define IDS_GR_CONMENU_INSERT_INITIALSTEP 4693
#define IDS_GR_CONMENU_INSERT_STEP      4694
#define IDS_GR_CONMENU_INSERT_ACTION    4695
#define IDS_GR_CONMENU_INSERT_TRANSITION 4696
#define IDS_GR_CONMENU_INSERT_ST_SYNTAX 4697
#define IDS_GR_CONMENU_VIEW_OBJHELP     4698
#define IDS_GR_CONMENU_SET_WATCHPOINT   4699
#define IDS_GR_CONMENU_CLEAR_WATCHPOINT 4700
#define IDS_GR_CONMENU_CLEAR_ALL_WATCHPOINTS 4701
#define IDS_GR_CONMENU_WRITE_WATCHPOINT 4702
#define IDS_GR_CONMENU_TOGGLE_BREAKPOINT 4703
#define IDS_GR_CONMENU_REMOVE_ALL_BREAKPOINTS 4704
#define IDS_GR_CONMENU_TOGGLE_BREAKPOINT_ENABLED 4705
#define IDS_GR_CONMENU_TOGGLE_MANUAL_MODE 4706
#define IDS_GR_CONMENU_CONTINUE_TASK    4707
#define IDS_GR_CONMENU_STEP_INTO        4708
#define IDS_GR_CONMENU_PERFORM_CYCLE    4709
#define IDS_GR_CONMENU_BOOKMARKSET      4710
#define IDS_GR_CONMENU_BOOKMARKNEXT     4711
#define IDS_GR_CONMENU_BOOKMARKPREV     4712
#define IDS_GR_CONMENU_FORCE_TRANSITION_ONCE 4713
#define IDS_GR_CONMENU_FORCE_TRANSITION 4714
#define IDS_GR_CONMENU_BLOCK_TRANSITION 4715
#define IDS_GR_CONMENU_FORCE_ALL_TRANSITIONS 4716
#define IDS_GR_CONMENU_BLOCK_ALL_TRANSITIONS 4717
#define IDS_GR_CONMENU_REVERT_ALL_TRANSITIONS 4718
#define IDS_GR_CONMENU_GLOBALLY_FORCE_ALL_TRANSITIONS 4719
#define IDS_GR_CONMENU_FORCE_ACTION_ONCE 4720
#define IDS_GR_CONMENU_FORCE_ACTION     4721
#define IDS_GR_CONMENU_BLOCK_ACTION     4722
#define IDS_GR_CONMENU_FORCE_ALL_ACTIONS 4723
#define IDS_GR_CONMENU_BLOCK_ALL_ACTIONS 4724
#define IDS_GR_CONMENU_REVERT_ALL_ACTIONS 4725
#define IDS_GR_CONMENU_GOBALLY_BLOCK_ALL_ACTIONS 4726
#define IDS_GR_CONMENU_EDIT_LINE         4727
#define IDS_GR_CONMENU_EDIT_INSTAMCE     4728
#define IDS_GR_CONMENU_EDIT_NAME         4729
#define IDS_GR_CONMENU_STEP_TOGGLEINIT   4730
#define IDS_GR_CONMENU_EDIT_ACT_NONE     4731
#define IDS_GR_CONMENU_INS_VARIN         4732
#define IDS_GR_CONMENU_INS_VAROUT        4733
#define IDS_GR_CONMENU_INS_VARINOUT      4734
#define IDS_GR_CONMENU_INS_JMP           4735
#define IDS_GR_CONMENU_INS_LAB           4736
#define IDS_GR_CONMENU_INS_RET           4737
#define IDS_GR_CONMENU_INS_CONOUT        4738
#define IDS_GR_CONMENU_INS_CONIN         4739
#define IDS_GR_CONMENU_INS_CMT           4740
#define IDS_GR_CONMENU_SUBMENU_FBD       4741
#define IDS_GR_CONMENU_INS_STEP          4742
#define IDS_GR_CONMENU_INS_TRANSITION    4743
#define IDS_GR_CONMENU_INS_ACTION        4744
#define IDS_GR_CONMENU_INS_ACTIONBLOCK   4745
#define IDS_GR_CONMENU_INS_DIVCON        4746
#define IDS_GR_CONMENU_INS_SDIVCON       4747
#define IDS_GR_CONMENU_INS_EXCEPTION_ACTION 4748
#define IDS_GR_CONMENU_INS_SUBMENU_SFC   4749
#define IDS_GR_CONMENU_INS_SUBMENU_LD    4750
#define IDS_GR_CONMENU_INS_POWER         4751
#define IDS_GR_CONMENU_CT_NORMAL         4752
#define IDS_GR_CONMENU_CT_CLOSED         4753
#define IDS_GR_CONMENU_CT_POSTRANS       4754
#define IDS_GR_CONMENU_CT_NEGTRANS       4755
#define IDS_GR_CONMENU_CL_NORMAL         4756
#define IDS_GR_CONMENU_CL_NEGATIVE       4757
#define IDS_GR_CONMENU_CL_SET            4758
#define IDS_GR_CONMENU_CL_RESET          4759
#define IDS_GR_CONMENU_CL_POSTRANS       4760
#define IDS_GR_CONMENU_CL_NEGTRANS       4761
#define IDS_GR_CONMENU_EDIT_COMMENT      4762
#define IDS_GR_CONMENU_EDIT_UNCOMMENT    4763
#define IDS_GR_CONMENU_EDIT_PROP_FBDACTION 4764
#define IDS_GR_CONMENU_EDIT_PROP_LDACTION  4765
#define IDS_GR_CONMENU_EDIT_PROP_STACTION  4766
#define IDS_GR_CONMENU_EDIT_PROPERTY     4767
#define IDS_GR_CONMENU_BOOKMARKCLEAR    4768
#define IDS_GR_DLG_PROPACT_QUAL_NONE    4769
#define IDS_GR_DLG_PROPACT_QUAL_N       4770
#define IDS_GR_DLG_PROPACT_QUAL_R       4771
#define IDS_GR_DLG_PROPACT_QUAL_S       4772
#define IDS_GR_DLG_PROPACT_QUAL_L       4773
#define IDS_GR_DLG_PROPACT_QUAL_D       4774
#define IDS_GR_DLG_PROPACT_QUAL_P       4775
#define IDS_GR_DLG_PROPACT_QUAL_SD      4776
#define IDS_GR_DLG_PROPACT_QUAL_DS      4777
#define IDS_GR_DLG_PROPACT_QUAL_SL      4778
#define IDS_GR_DLG_PROPACT_QUAL_P0      4779
#define IDS_GR_DLG_PROPACT_QUAL_P1      4780
#define IDS_GR_DLG_PROPVAR_TYPE_VARREAD 4781
#define IDS_GR_DLG_PROPVAR_TYPE_VARWRITE 4782
#define IDS_GR_DLG_PROPVAR_TYPE_VARFEEDBACK 4783
#define IDS_GR_DLG_PROPLD_TYPE_CONTACT  4784
#define IDS_GR_DLG_PROPLD_TYPE_CONTACT_C  4785
#define IDS_GR_DLG_PROPLD_TYPE_CONTACT_P  4786
#define IDS_GR_DLG_PROPLD_TYPE_CONTACT_N  4787
#define IDS_GR_DLG_PROPCOIL_TYPE_NORMAL   4788
#define IDS_GR_DLG_PROPCOIL_TYPE_NEGATIVE 4789
#define IDS_GR_DLG_PROPCOIL_TYPE_POSTRAN  4790
#define IDS_GR_DLG_PROPCOIL_TYPE_NEGTRAN  4791
#define IDS_GR_DLG_PROPCOIL_TYPE_SET      4792
#define IDS_GR_DLG_PROPCOIL_TYPE_RESET    4793
#define IDS_GR_STACTION_WARN_YN           4794
#define IDS_GR_CONMENU_STEP_OVER          4795
#define IDS_GR_CONMENU_STEP_OUT           4796
#define IDS_GR_CANNOT_STEP_OVER           4797
#define IDS_GR_CANNOT_STEP_OUT            4798

#define IDD_GR_PRINT_OPTIONS            6009
#define IDC_HEADER_CHECK                6103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        4099
#define _APS_NEXT_COMMAND_VALUE         4665
#define _APS_NEXT_CONTROL_VALUE         4186
#define _APS_NEXT_SYMED_VALUE           4005
#endif
#endif
