//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by STEditor.rc
//
#define STEDITOR_RESOURCEBASE           6000
#define IDR_STTYPE_SRVR_IP              6001
#define IDR_STTYPE_SRVR_EMB             6002
#define IDD_ABOUTBOX                    6003
#define IDP_OLE_INIT_FAILED             6004
#define IDR_MAINFRAME                   6005
#define IDR_STTYPE                      6006
#define IDD_PRINT_OPTIONS               6009
#define IDD_GOTOLINE                    6020
#define IDD_EDITVARIABLE                6021
#define IDD_FIND_HELP_ID                6022
#define IDD_REPLACE_HELP_ID             6023
#define IDD_EDITOR_SETTINGS             6024
#define IDC_LINE_NUMBER                 6100
#define IDC_VARVALUE                    6101
#define IDC_APPLY                       6102
#define IDC_VARNAME                     6103
#define IDC_HEADER_CHECK                6104
#define IDC_ES_KEEPTABS_CHK             6105
#define IDC_ES_TABSIZE_EDT              6106
#define IDC_ES_DEFTEXTCOL_BTN           6107
#define IDC_ES_QUOTECOL_BTN             6108
#define IDC_ES_COMMENTCOL_BTN           6109
#define IDC_ES_BGCOL_BTN                6110
#define IDC_ES_KEYWORDCOL_BTN           6111
#define IDC_ES_DEFAULT_BTN              6112
#define ID_CANCEL_EDIT_SRVR             6200
#define IDM_GOTO_LINE                   6201
#define IDM_SET_WATCHPOINT              6202
#define IDM_CLEAR_WATCHPOINT            6203
#define IDM_CLEAR_ALL_WATCHPOINTS       6204
#define IDM_TOGGLE_BREAKPOINT           6205
#define IDM_TOGGLE_BREAKPOINT_ENABLED   6206
#define IDM_INSERT_FB_CALL              6207
#define IDM_CONTINUE_TASK               6208
#define IDM_STEP_INTO                   6209
#define IDM_INSERT_IF                   6210
#define IDM_INSERT_CASE                 6211
#define IDM_INSERT_FOR                  6212
#define IDM_INSERT_WHILE                6213
#define IDM_INSERT_REPEAT               6214
#define IDM_INSERT_ASSIGNMENT           6215
#define IDM_INSERT_RETURN               6216
#define IDM_INSERT_EXIT                 6217
#define IDM_INSERT_VAR                  6218
#define IDM_REMOVE_ALL_BREAKPOINTS      6219
#define IDM_SHOW_VAR_SELECTION          6220
#define IDM_WRITE_WATCHPOINT            6221
#define ID_EDIT_SCROLL_DOWN             6222
#define ID_EDIT_SCROLL_UP               6223
#define IDM_INSERT_INITIALSTEP          6224
#define IDM_INSERT_STEP                 6225
#define IDM_INSERT_ACTION               6226
#define IDM_INSERT_TRANSITION           6227
#define IDM_TOGGLE_MANUAL_MODE          6228
#define IDM_PERFORM_CYCLE               6229
#define IDM_FORCE_TRANSITION_ONCE       6230
#define IDM_FORCE_TRANSITION            6231
#define IDM_BLOCK_TRANSITION            6232
#define IDM_FORCE_ALL_TRANSITIONS       6233
#define IDM_BLOCK_ALL_TRANSITIONS       6234
#define IDM_REVERT_ALL_TRANSITIONS      6235
#define IDM_GLOBALLY_FORCE_ALL_TRANSITIONS 6236
#define IDM_FORCE_ACTION_ONCE           6237
#define IDM_FORCE_ACTION                6238
#define IDM_BLOCK_ACTION                6239
#define IDM_FORCE_ALL_ACTIONS           6240
#define IDM_BLOCK_ALL_ACTIONS           6241
#define IDM_REVERT_ALL_ACTIONS          6242
#define IDM_GLOBALLY_BLOCK_ALL_ACTIONS  6243
#define IDM_INSERT_RET                  6244
#define IDM_INSERT_LDN                  6245
#define IDM_VIEW_OBJHELP                6246
#define IDM_INSERT_LRU_FIRST            6247
#define IDM_INSERT_LRU_LAST             6267
#define IDM_XREF_LAST                   6268
#define IDM_XREF_NEXT                   6269
#define IDM_XREF_QUERY                  6270
#define IDM_SHOW_VAR_SEL_POPUP          6271
#define IDM_INSERT_CONST                6272
#define IDM_INSERT_VAR_GLOBAL           6273
#define IDM_INSERT_VAR_EXTERNAL         6274
#define IDM_CONTEXT_MENU                6275
#define IDM_INSERT_LD                   6278
#define IDM_INSERT_ST                   6279
#define IDM_INSERT_S                    6280
#define IDM_INSERT_R                    6281
#define IDM_INSERT_ADD                  6282
#define IDM_INSERT_SUB                  6283
#define IDM_INSERT_MUL                  6284
#define IDM_INSERT_DIV                  6285
#define IDM_INSERT_GT                   6286
#define IDM_INSERT_GE                   6287
#define IDM_INSERT_EQ                   6288
#define IDM_INSERT_NE                   6289
#define IDM_INSERT_LE                   6290
#define IDM_INSERT_LT                   6291
#define IDM_INSERT_CAL                  6293
#define IDM_INSERT_JMP                  6292
#define IDM_INSERT_STN                  6296
#define IDM_INSERT_AND                  6297
#define IDM_INSERT_ANDN                 6298
#define IDM_INSERT_OR                   6299
#define IDM_INSERT_ORN                  6300
#define IDM_INSERT_XOR                  6301
#define IDM_INSERT_XORN                 6302
#define IDM_INSERT_CALC                 6303
#define IDM_INSERT_CALCN                6304
#define IDM_INSERT_JMPC                 6305
#define IDM_INSERT_JMPCN                6306
#define IDM_INSERT_RETC                 6307
#define IDM_INSERT_RETCN                6308
#define IDM_STEP_OVER                   6309
#define IDM_STEP_OUT                    6310
#define IDM_EDIT_FORMATSEL              6311
#define IDM_EDIT_SETTINGS               6312
#define IDS_LOADVAR                     6330
#define IDS_SEARCH_STRING_NOT_FOUND     6331
#define IDS_CANNOT_CONTINUE_TASK        6332
#define IDS_CANNOT_STEP_INTO            6333
#define IDS_CANNOT_SET_MANUAL_MODE      6334
#define IDS_CANNOT_RESET_MANUAL_MODE    6335
#define IDS_CANNOT_PERFORM_CYCLE        6336
#define IDS_CANNOT_FORCE_TRANSITION     6337
#define IDS_CANNOT_BLOCK_TRANSITION     6338
#define IDS_CANNOT_FORCE_ACTION         6339
#define IDS_CANNOT_BLOCK_ACTION         6340
#define IDS_CANNOT_FORCE_TRANSITIONS    6341
#define IDS_CANNOT_BLOCK_TRANSITIONS    6342
#define IDS_CANNOT_REVERT_TRANSITIONS   6343
#define IDS_CANNOT_FORCE_ACTIONS        6344
#define IDS_CANNOT_BLOCK_ACTIONS        6345
#define IDS_CANNOT_REVERT_ACTIONS       6346
#define IDS_READONLY_WARNING            6347
#define IDS_FILE_READ_ONLY              6348
#define IDS_CONMENU_EDIT_CUT            6349
#define IDS_CONMENU_EDIT_COPY           6350
#define IDS_CONMENU_EDIT_PASTE          6351
#define IDS_CONMENU_EDIT_CLEAR          6352
#define IDS_CONMENU_INSERT_FB_CALL      6353
#define IDS_CONMENU_INSERT_LRU_FIRST    6354
#define IDS_CONMENU_SHOW_VAR_SELECTION  6355
#define IDS_CONMENU_SHOW_VAR_SEL_POPUP  6356
#define IDS_CONMENU_XREF_QUERY          6357
#define IDS_CONMENU_XREF_LAST           6358
#define IDS_CONMENU_XREF_NEXT           6359
#define IDS_CONMENU_INSERT_VAR          6360
#define IDS_CONMENU_INSERT_CONST        6361
#define IDS_CONMENU_INSERT_VAR_GLOBAL   6362
#define IDS_CONMENU_INSERT_VAR_EXTERNAL 6363
#define IDS_CONMENU_INSERT_ASSIGNMENT   6364
#define IDS_CONMENU_INSERT_IF           6365
#define IDS_CONMENU_INSERT_CASE         6366
#define IDS_CONMENU_INSERT_FOR          6367
#define IDS_CONMENU_INSERT_WHILE        6368
#define IDS_CONMENU_INSERT_REPEAT       6369
#define IDS_CONMENU_INSERT_RETURN       6370
#define IDS_CONMENU_INSERT_EXIT         6371
#define IDS_CONMENU_INSERT_INITIALSTEP  6372
#define IDS_CONMENU_INSERT_STEP         6373
#define IDS_CONMENU_INSERT_ACTION       6374
#define IDS_CONMENU_INSERT_TRANSITION   6375
#define IDS_CONMENU_INSERT_ST_SYNTAX    6376
#define IDS_CONMENU_VIEW_OBJHELP        6377
#define IDS_CONMENU_SET_WATCHPOINT      6378
#define IDS_CONMENU_CLEAR_WATCHPOINT    6379
#define IDS_CONMENU_CLEAR_ALL_WATCHPOINTS 6380
#define IDS_CONMENU_WRITE_WATCHPOINT    6381
#define IDS_CONMENU_TOGGLE_BREAKPOINT   6382
#define IDS_CONMENU_REMOVE_ALL_BREAKPOINTS 6383
#define IDS_CONMENU_TOGGLE_BREAKPOINT_ENABLED 6384
#define IDS_CONMENU_TOGGLE_MANUAL_MODE  6385
#define IDS_CONMENU_CONTINUE_TASK       6386
#define IDS_CONMENU_STEP_INTO           6387
#define IDS_CONMENU_PERFORM_CYCLE       6388
#define IDS_CONMENU_BOOKMARKSET         6389
#define IDS_CONMENU_BOOKMARKNEXT        6390
#define IDS_CONMENU_BOOKMARKPREV        6391
#define IDS_CONMENU_FORCE_TRANSITION_ONCE 6392
#define IDS_CONMENU_FORCE_TRANSITION    6393
#define IDS_CONMENU_BLOCK_TRANSITION    6394
#define IDS_CONMENU_FORCE_ALL_TRANSITIONS 6395
#define IDS_CONMENU_BLOCK_ALL_TRANSITIONS 6396
#define IDS_CONMENU_REVERT_ALL_TRANSITIONS 6397
#define IDS_CONMENU_GLOBALLY_FORCE_ALL_TRANSITIONS 6398
#define IDS_CONMENU_FORCE_ACTION_ONCE   6399
#define IDS_CONMENU_FORCE_ACTION        6400
#define IDS_CONMENU_BLOCK_ACTION        6401
#define IDS_CONMENU_FORCE_ALL_ACTIONS   6402
#define IDS_CONMENU_BLOCK_ALL_ACTIONS   6403
#define IDS_CONMENU_REVERT_ALL_ACTIONS  6404
#define IDS_CONMENU_GOBALLY_BLOCK_ALL_ACTIONS 6405
#define IDS_ERRMSG_WRONG_VAR_SYNTAX     6406
#define IDS_ERRMSG_WRONG_VALUE_SYNTAX   6407
#define IDS_ERRMSG_FAILED_TO_WRITE_VAR  6408
#define IDS_SFC_ACTION_TEXT_BLOCKED     6409
#define IDS_SFC_ACTION_TEXT_FORCED      6410
#define IDS_SFC_ACTION_TEXT_FORCED_PERMANENTLY 6411
#define IDS_CONMENU_INSERT_IL_SYNTAX    6412
#define IDS_CONMENU_INSERT_LD           6413
#define IDS_CONMENU_INSERT_ST           6414
#define IDS_CONMENU_INSERT_S            6415
#define IDS_CONMENU_INSERT_R            6416
#define IDS_CONMENU_INSERT_ADD          6417
#define IDS_CONMENU_INSERT_SUB          6418
#define IDS_CONMENU_INSERT_MUL          6419
#define IDS_CONMENU_INSERT_DIV          6420
#define IDS_CONMENU_INSERT_GT           6421
#define IDS_CONMENU_INSERT_GE           6422
#define IDS_CONMENU_INSERT_EQ           6423
#define IDS_CONMENU_INSERT_NE           6424
#define IDS_CONMENU_INSERT_LE           6425
#define IDS_CONMENU_INSERT_LT           6426
#define IDS_CONMENU_INSERT_JMP          6427
#define IDS_CONMENU_INSERT_CAL          6428
#define IDS_CONMENU_INSERT_RET          6429
#define IDS_CONMENU_INSERT_LDN          6430
#define IDS_CONMENU_INSERT_STN          6431
#define IDS_CONMENU_INSERT_AND          6432
#define IDS_CONMENU_INSERT_ANDN         6433
#define IDS_CONMENU_INSERT_OR           6434
#define IDS_CONMENU_INSERT_ORN          6435
#define IDS_CONMENU_INSERT_XOR          6436
#define IDS_CONMENU_INSERT_XORN         6437
#define IDS_CONMENU_INSERT_CALC         6438
#define IDS_CONMENU_INSERT_CALCN        6439
#define IDS_CONMENU_INSERT_JMPC         6440
#define IDS_CONMENU_INSERT_JMPCN        6441
#define IDS_CONMENU_INSERT_RETC         6442
#define IDS_CONMENU_INSERT_RETCN        6443
#define IDS_CONMENU_STEP_OVER           6444
#define IDS_CONMENU_STEP_OUT            6445
#define IDS_CANNOT_STEP_OVER            6446
#define IDS_CANNOT_STEP_OUT             6447
#define IDS_CONMENU_FORMATSEL           6448
#define IDS_CONMENU_EDITOR_SETTINGS     6449
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        6012
#define _APS_NEXT_COMMAND_VALUE         6313
#define _APS_NEXT_CONTROL_VALUE         6113
#define _APS_NEXT_SYMED_VALUE           6007
#endif
#endif
