#ifndef __PROJECTWIZARDLIBRARY_H_
#define __PROJECTWIZARDLIBRARY_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000


//----  Aggregate Includes:   --------------------------------------*
#include "ProjectWizardDefs.h"

//----  Forward Class Definitions:   -------------------------------*

//----  Defines:    ------------------------------------------------*

//----  Globals:    ------------------------------------------------*

//----  Prototypes:    ---------------------------------------------*


class CProjectWizardLibrary
{
public:
    CProjectWizardLibrary ();

    CString GetLibraryName ();
    void SetLibraryName (CString strLibraryName);

    BOOL GetSelectFlag ();
    void SetSelectFlag (BOOL bSelectFlag);

    TSubSystems GetSubSystemDefault ();

protected:
    CString     m_strLibraryName;
    BOOL        m_bSelectFlag;
    TSubSystems m_subSystemDefault;
};

#endif // __PROJECTWIZARDLIBRARY_H_


/*
 *----------------------------------------------------------------------------*
 *  $History: ProjectWizardLibrary.h $
 * 
 * *****************  Version 1  *****************
 * User: Ln           Date: 28.02.07   Time: 18:57
 * Created in $/4CReleased/V2.20.00/COM/softing/fc/CE/CEWiz/inc
 * 
 * *****************  Version 1  *****************
 * User: Ln           Date: 28.08.03   Time: 16:30
 * Created in $/4Control/COM/softing/fc/CE/CEWiz/inc
 * 
 * *****************  Version 2  *****************
 * User: Rf           Date: 15.05.01   Time: 20:25
 * Updated in $/4Control/COM/softing/fc/CE/CEWiz/inc
 * 
 * *****************  Version 1  *****************
 * User: Rf           Date: 15.05.01   Time: 14:12
 * Created in $/4Control/COM/softing/fc/CE/CEWiz/inc
 *==
 *----------------------------------------------------------------------------*
*/

// 10.05.2001  Generated by VC++6.0 VBScript 'ToF Macros.dsm' Version 1.0/Je
// ***************************  E O F  ******************************
// $Workfile: ProjectWizardLibrary.h $
