

#if !defined(AFX_PROJMANEVENTSIMPL_H__A8143747_3A0C_4875_84F9_AD80BFEBCAA2__INCLUDED_)
#define AFX_PROJMANEVENTSIMPL_H__A8143747_3A0C_4875_84F9_AD80BFEBCAA2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "CEProjMan.h"



class CPouVarSelData;


//------------------------------------------------------------------*
/**
 * CProjManEventsImpl reacts to events generated by the project
 * manager. The only event of interest is the change of the class tree.
 * The dlg data has to be refreshed after that.
 *
 * @see             
*/
class CProjManEventsImpl : public IDispatchImpl<_ICEProjectManagerEvents, 
                                                &IID__ICEProjectManagerEvents, 
                                                &LIBID_CEPROJMANLib>,
						   public CComObjectRoot
{
public:
	CProjManEventsImpl();
	virtual ~CProjManEventsImpl();

public:
    void SetPouVarSelDataPtr(CPouVarSelData* pPouVarSelData);

protected:
    // pointer to the object holding the base data for the dialogs
    // this is needed to inform that object that there has been changes
    CPouVarSelData* m_pPouVarSelData;

private:
    STDMETHOD (InitClassTree)(IUnknown* pXMLDocument);
    STDMETHOD (InitTargetTree)(IUnknown* pXMLDocument );  
    STDMETHOD (InitInstanceTree)(IUnknown* pXMLDocument );  
    STDMETHOD (UpdateClassTree)(BSTR sChangedIdPath, enum E_UPDATE_MODE eMode);
    STDMETHOD (UpdateTargetTree)(BSTR sChangedIdPath, enum E_UPDATE_MODE eMode);
    STDMETHOD (UpdateInstanceTree)(BSTR sChangedIdPath, enum E_UPDATE_MODE eMode);
    STDMETHOD (OnFileAdded)(BSTR sFilePath, enum E_FV_FileCategory eFileCat);
    STDMETHOD (OnFileRemoved)(BSTR sFilePath, enum E_FV_FileCategory eFileCat);
    STDMETHOD (ShowContextHelp)(DWORD dwContextId);
    STDMETHOD (ProjectFileChanged)();


	BEGIN_COM_MAP(CProjManEventsImpl)
	    COM_INTERFACE_ENTRY(_ICEProjectManagerEvents)
   	    COM_INTERFACE_ENTRY(IDispatch)
	END_COM_MAP()

};

#endif // !defined(AFX_PROJMANEVENTSIMPL_H__A8143747_3A0C_4875_84F9_AD80BFEBCAA2__INCLUDED_)


