(*[[
    GUID= "{E2284DED-50ED-40C8-A875-7814E078DBA3}",  
    Alias="alias",
    Created="created",
    Modified="modified",
    UserCreated="usrcreated",
    UserModified="usrmodified",
    UserHelpURL="url",
    UserURL="url",
    UserText1="usertext1",
    UserText2="usertext2",
    UserText3="usertext3",
    KEY_001="VALUE_001",
    KEY_002="VALUE_002",
    KEY_003="VALUE_003",
]]*)

FUNCTION function_001 : DT


VAR_INPUT
    input_none : DINT;
END_VAR


;

END_FUNCTION

