/*H>> $Header: /4CReleased/V2.20.00/COM/softing/fc/CMN/fc_baselib/time.cpp 1     28.02.07 19:00 Ln $
 *----------------------------------------------------------------------------*
 *
 * =FILENAME            $Workfile: time.cpp $
 *                       $Logfile: /4CReleased/V2.20.00/COM/softing/fc/CMN/fc_baselib/time.cpp $
 *
 * =PROJECT             7VH102  ATCMControl
 *
 * =SWKE                CMN
 *
 * =COMPONENT           BASELIB
 *
 * =CURRENT      $Date: 28.02.07 19:00 $
 *           $Revision: 1 $
 *
 * =ENVIRONMENT             Win32:
 *                      MS Windows NT 4.0
 *                      MSVC++ V6.0 / MFC 6.0 / ATL 3.0 / DAO 3.5
 *                      MS Java 2.0
 *                      MS Visual SourceSafe 5.0/6.0
 *
 * =REFERENCES
 *==
 *----------------------------------------------------------------------------*
 *

 *                http://www.4control.de

 

 *==
 *----------------------------------------------------------------------------*
 * =DESCRIPTION
 *    @DESCRIPTION@
 *==
 *----------------------------------------------------------------------------*
 * =MODIFICATION
 *  04.02.99  Je      File created
 *  see history at end of file !
 *==
 *******************************************************************************
H<<*/



#include "stdafx.h"
#define BASELIB_API __declspec(dllexport)
#define UNICODE 1
#define _UNICODE 1

#include "baselib.h"
#include <math.h>

//----  Local Defines:   -------------------------------------------*

//----  Static Initializations:   ----------------------------------*
#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif



//----  Local Prototypes:   ----------------------------------------*




//------------------------------------------------------------------*
/**
 * BL_SystemTimeToVariantTime
 *  corrects the Win32-supplied SystemTimeToVariantTime: no truncation of
 *  fractions below seconds
 *
 * @param           pSystemTime     contains system time to convert to DATE
 * @param           pvTime          converted time *WITH* milliseconds in fraction!
 * @return          nonzero if function succeeds
 * @exception       -
 * @see             
*/
extern "C"
HRESULT BASELIB_API __stdcall
    BL_SystemTimeToVariantTime(SYSTEMTIME const * pSys, OUT DOUBLE *pvTime)
{
    if ((pSys == NULL) || (pvTime == NULL)) {
        return E_POINTER;
    }

    // give the time without millis to SystemTimeToVariantTime
    DOUBLE raw;
    SYSTEMTIME t0 = *pSys;
    t0.wMilliseconds = 0;
    HRESULT hr = SystemTimeToVariantTime(&t0, &raw);

    // and add the milliseconds later
    DOUBLE delta = pSys->wMilliseconds / (24.0 * 3600000.0);

    *pvTime = raw + delta;

    return hr;
}


/*
 *----------------------------------------------------------------------------*
 *  $History: time.cpp $
 * 
 * *****************  Version 1  *****************
 * User: Ln           Date: 28.02.07   Time: 19:00
 * Created in $/4CReleased/V2.20.00/COM/softing/fc/CMN/fc_baselib
 * 
 * *****************  Version 1  *****************
 * User: Ln           Date: 28.08.03   Time: 16:33
 * Created in $/4Control/COM/softing/fc/CMN/fc_baselib
 * 
 * *****************  Version 1  *****************
 * User: Ef           Date: 23.01.01   Time: 17:12
 * Created in $/4Control/COM/softing/fc/CMN/fc_baselib
 * utils and baselib from V1.3
 * 
 * *****************  Version 2  *****************
 * User: Ed           Date: 2.12.99    Time: 10:05
 * Updated in $/4Control/COM/softing/fc/CMN/baselib
 * avoid possible rounding issues
 * 
 * *****************  Version 1  *****************
 * User: Je           Date: 4.02.99    Time: 17:13
 * Created in $/4Control/COM/softing/fc/CMN/baselib
 * * fixed d-1342: show watch values with msecs resolution
 *==
 *----------------------------------------------------------------------------*
*/

// 04.02.99  Generated by VC++6.0 VBScript '4C Macros.dsm' Version 1.3/Je
// ***************************  E O F  ******************************
// $Workfile: time.cpp $
