
/*****************************************************************************/
/*                          KEYWORDS                                         */
/*                                                                           */
/*  Filename    : KEYWORDS.H                                                 */
/*  Version     : 5.21.0.00.release                                          */
/*  Date        : 27-February-1998                                           */
/*                                                                           */
/*  Description : This include file defines some keywords which are used     */
/*  for structuring and formatting the PROFIBUS source files. These          */
/*  keywords are ignored by the the compiler.                                */
/*                                                                           */
/*****************************************************************************/


#ifndef __KEYWORDS__
#define __KEYWORDS__

#define INCLUDES
#define GLOBAL_DEFINES
#define LOCAL_DEFINES
#define EXPORT_TYPEDEFS
#define LOCAL_TYPEDEFS
#define EXPORT_DATA
#define IMPORT_DATA
#define LOCAL_DATA
#define FUNCTION
#define IN
#define OUT
#define INOUT
#define FUNCTIONAL_DESCRIPTION
#define ASSERTIONS
#define LOCAL_VARIABLES
#define FUNCTION_BODY
#define FUNCTION_DECLARATIONS
#define PUBLIC
#define GLOBAL

#endif
