#include "stdafx.h"

#include "Methods.h"

const TCHAR * DISP_IDS[] = {
    _T("AddLibrary"),//0
    _T("DeleteConstantList"),//1
    _T("DeleteFunction"),//2
    _T("DeleteFunctionBlock"),//3
    _T("DeleteGlobalVariableList"),//4
    _T("DeleteGlobalVariableListRef"),//5
    _T("DeleteIoComponentOpc"),//6
    _T("DeleteIoComponentPb"),//7
    _T("DeleteVariable"),//8 d-186 07.02.05 SIS: removed DeletePc and reused entry for DeleteVariable
    _T("DeleteProgram"),//9
    _T("DeleteProgramInstance"),//10
    _T("DeleteResource"),//11
    _T("DeleteStructure"),//12
    _T("DeleteTask"),//13
    _T("DragFunction"),//14
    _T("DragFunctionBlock"),//15
    _T("DragProgram"),//16
    _T("DragProgramInstance"),//17
    _T("DragResource"),//18
    _T("DragVariable"),//19
    _T("DropProgram"),//20
    _T("EditConstantList"),//21
    _T("EditFunction"),//22
    _T("EditFunctionBlock"),//23
    _T("EditGlobalVariableList"),//24
    _T("EditPcName"),//25
    _T("EditProgram"),//26
    _T("EditProgramInstance"),//27
    _T("EditResource"),//28
    _T("EditStructure"),//29
    _T("EditTask"),//30
    _T("EditVariable"),//31
    _T("InsertConstant"),//32
    _T("InsertConstantList"),//33
    _T("InsertStructure"),//34
    _T("InsertIoComponentOpc"),//35
    _T("InsertIoComponentPb"),//36
    _T("InsertFunction"),//37
    _T("InsertFunctionBlock"),//38
    _T("InsertGlobalVariable"),//39
    _T("InsertGlobalVariableList"),//40
    _T("InsertGlobalVariableListRef"),//41
    _T("InsertPc"),//42
    _T("InsertProgram"),//43
    _T("InsertProgramInstance"),//44
    _T("InsertResource"),//45
    _T("InsertTask"),//46
    _T("Open4cConfigurator"),//47
    _T("OpenConsole"),//48
    _T("OpenLibrary"),//49
    _T("OpenUserHelp"),//50
    _T("PropertiesConstantList"),//51
    _T("PropertiesFunction"),//52
    _T("PropertiesFunctionBlock"),//53
    _T("PropertiesGlobalVariableList"),//54
    _T("PropertiesIoComponentOpc"),//55
    _T("PropertiesIoComponentPb"),//56
    _T("PropertiesResource"),//57
    _T("PropertiesStructure"),//58
    _T("PropertiesTask"),//59
    _T("PropertiesPc"),//60
    _T("PropertiesProgram"),//61
    _T("PropertiesResource"),//62
    _T("RemoveLibrary"),//63
    _T("RenameFunction"),//64
    _T("RenameFunctionBlock"),//65
    _T("RenameProgram"),//66
    _T("RenameProgramInstance"),//67
    _T("RenameResource"),//68
    _T("RenameStructure"),//69
    _T("RenameTask"),//70
    _T("StartControl"),//71
    _T("StartTask"),//72
    _T("StopControl"),//73
    _T("StopTask"),//74
    _T("WatchFunctionBlock"),//75
    _T("WatchGlobalVariableList"),//76
    _T("WatchProgramInstance"),//77
    _T("WatchVariableType"),//78
    _T("PropertiesProgramInstance"),//79
    _T("ProjectProperties"),//80

    _T("")
};
