/*
 * generated by gen_XML_4GR_Names.pl,
 * from "c:\4control/COM/softing/fc/inc/XML_4GR_Names.h"
 * at Thu Jun 17 09:41:12 1999
 */


import com.ms.xml.util.Name;
class Fbd_XML_4GR_Names
{
   static final Name ELEM_FCPOU = Name.create("FCPOU"); // added by generator
   //XML Element and Attribute names used in 4GR Files
   //NOTE: all Elemet and Attribute names must be uppercase
   //to be compatible with msxml.dll version 4.
   //Attribute values shall be all lower case.
   //Element names:
   static final Name ELEM_HEADER          = Name.create("HEADER");
   static final Name ELEM_BODY            = Name.create("BODY");
   static final Name ELEM_EDITINFO        = Name.create("EDITINFO");
   static final Name ELEM_LINE            = Name.create("LINE");
   static final Name ELEM_VARREAD         = Name.create("VARREAD");
   static final Name ELEM_VARWRITE        = Name.create("VARWRITE");
   static final Name ELEM_VARFEEDBACK     = Name.create("VARFEEDBACK");
   static final Name ELEM_PRO             = Name.create("PRO");
   static final Name ELEM_FNC             = Name.create("FNC");
   static final Name ELEM_FB              = Name.create("FB");
   static final Name ELEM_PIN             = Name.create("PIN");
   static final Name ELEM_PINLIST         = Name.create("PINLIST");
   static final Name ELEM_LABEL           = Name.create("LABEL");
   static final Name ELEM_JUMP            = Name.create("JUMP");
   static final Name ELEM_RETURN          = Name.create("RETURN");
   static final Name ELEM_CONNECTOR       = Name.create("CONNECTOR");
   static final Name ELEM_CONTINUATION    = Name.create("CONTINUATION");
   static final Name ELEM_STEP            = Name.create("STEP");
   static final Name ELEM_TRANS           = Name.create("TRANS");
   static final Name ELEM_ALTDIV          = Name.create("ALTDIV");
   static final Name ELEM_SIMDIV          = Name.create("SIMDIV");
   static final Name ELEM_ACTION          = Name.create("ACTION");
   static final Name ELEM_ACTBLCK         = Name.create("ACTBLCK");
   static final Name ELEM_ACTQUAL         = Name.create("ACTQUAL");
   static final Name ELEM_COMMENT         = Name.create("COMMENT");
   static final Name ELEM_OBJCOMMENT      = Name.create("OBJCOMMENT");   
   //Attribute names:
   static final Name ATTR_EDITNAME        = Name.create("EDITNAME");
   static final Name ATTR_EDITVERSION     = Name.create("EDITVERSION");
   static final Name ATTR_EDITCATID       = Name.create("EDITCATID");
   static final Name ATTR_EDITCLASSID     = Name.create("EDITCLASSID");
   static final Name ATTR_LANG            = Name.create("LANG");
   static final Name ATTR_ORIGIN          = Name.create("ORIGIN");
   static final Name ATTR_INORIGIN        = Name.create("INORIGIN");
   static final Name ATTR_OUTORIGIN       = Name.create("OUTORIGIN");
   static final Name ATTR_SIZE            = Name.create("SIZE");
   static final Name ATTR_NAME            = Name.create("NAME");
   static final Name ATTR_TYPE            = Name.create("TYPE");
   static final Name ATTR_TYPENAME        = Name.create("TYPENAME");
   static final Name ATTR_VERSIONID       = Name.create("VERSIONID");
   static final Name ATTR_SELECTED        = Name.create("SELECTED");
   static final Name ATTR_HIDEPINNAMES    = Name.create("HIDEPINNAMES");
   static final Name ATTR_BORDER          = Name.create("BORDER");
   static final Name ATTR_CLASS           = Name.create("CLASS");
   static final Name ATTR_INITVAL         = Name.create("INITVAL");
   static final Name ATTR_INITSTEP        = Name.create("INITSTEP");
   static final Name ATTR_RUBBERLINE      = Name.create("RUBBERLINE");
   static final Name ATTR_NEGATE          = Name.create("NEGATE");
   static final Name ATTR_HIDDED          = Name.create("HIDDED");
   static final Name ATTR_CENTRE_X        = Name.create("CENTRE_X");
   static final Name ATTR_CENTRE_Y        = Name.create("CENTRE_Y");
   static final Name ATTR_DISABLE         = Name.create("DISABLE");
   static final Name ATTR_R_EDGE          = Name.create("R_EDGE");
   static final Name ATTR_F_EDGE          = Name.create("F_EDGE");
   static final Name ATTR_QUALTYPE        = Name.create("QUALTYPE");
   static final Name ATTR_QUALTIME        = Name.create("QUALTIME");
   static final Name ATTR_COMMENT         = Name.create("COMMENT");
   static final Name ATTR_OBJCOMMENT      = Name.create("OBJCOMMENT");
   static final Name ATTR_ID              = Name.create("ID");   
   //Attribute Values of attribute CLASS
   static final Name ATTR_VAL_INPUT       = Name.create("input");
   static final Name ATTR_VAL_OUTPUT      = Name.create("output");
   static final Name ATTR_VAL_INOUTPUT    = Name.create("inoutput");
   static final Name ATTR_VAL_INEXT       = Name.create("inext");
   static final Name ATTR_VAL_OUTEXT      = Name.create("outext");
   //Attribute Values of attribute LANG
   static final Name ATTR_VAL_FBD         = Name.create("fbd");
   static final Name ATTR_VAL_LD          = Name.create("ld");
   static final Name ATTR_VAL_FBD_SFC     = Name.create("fbd_sfc");
   static final Name ATTR_VAL_LD_SFC      = Name.create("ld_sfc");
   static final Name ATTR_VAL_ALL         = Name.create("all");
   //
   //Elements & Attr speciffic for the clibboard format:
   //
   //Header
   //Attributes header
   //Const
}
