


setlocal
if "%PROJECT_ROOT%" == "" goto bad_dir
if not exist %PROJECT_ROOT%\nul goto bad_dir
if "%EXE_DIR%" == "" set EXE_DIR=%PROJECT_ROOT%
if "%PANEL_DIR%" == "" set PANEL_DIR=%EXE_DIR%\console
if not exist %PANEL_DIR%\nul md %PANEL_DIR%


if "%1" == "SIGN" goto production
if "%1" == "sign" goto production
if "%1" == "CHECK" goto check
if "%1" == "check" goto check
goto unsigned


rem ******************************************************************
:production
echo *---- Do Official Signing of EXEs:
echo ... Signing Setup4C.exe...

signcode -n "ATCM Setup Tool" -i http://www.4control.de -spc \\sfiler\IAD_4CONTROL\ProductGen\SetupGen\Zertifikate\VeriSign\CredVeriSign.spc -v \\sfiler\IAD_4CONTROL\ProductGen\SetupGen\Zertifikate\VeriSign\SoftingKey.pvk %EXE_DIR%\Pub\Setup4C.exe
echo ... Timestamping INSTTOOL.exe...
signcode -t http://timestamp.verisign.com/scripts/timstamp.dll -x %EXE_DIR%\Pub\Setup4C.exe

echo ... Checking Trust of EXEs...
echo Checking Trust of Setup4C.exe.......
chktrust -q %EXE_DIR%\Pub\Setup4C.exe

goto end

rem ******************************************************************
:check
echo ... Checking Trust of EXEs...
echo Checking Trust of Setup4C.exe...
chktrust %EXE_DIR%\Pub\Setup4C.exe
goto end

rem ******************************************************************
:unsigned
echo *---- Creating certificate (test only!) ...
makecert -n "CN=ATCM (vo)" -sv vo.pvk vo.cer
echo ... Converting certificate...
cert2spc vo.cer vo.spc

echo ... Signing Setup4C.exe...
signcode -n "ATCM InstallTool" -i http://www.4control.de -spc vo.spc -v vo.pvk %EXE_DIR%\Pub\Setup4C.exe
goto end

:bad_dir
    echo Bad project root directoy: %PROJECT_ROOT%. Check your ATCM project environment settings!
    goto end

:end
endlocal

rem *----------------------------------------------------------------------------*
rem * =MODIFICATIONS
rem *==
rem *----------------------------------------------------------------------------*
rem * 1998-08-20/Je  Generated by PERL5 script d:\bin\perl5/mkproto.bat Version 1.2
rem * ***************************  E O F  ******************************
rem * $Workfile: signINST.bat $
