


// This file will be processed by the MIDL compiler to produce the
// type library (ConfigOPC.tlb).

[ 
    uuid(33146a04-b51c-4267-9864-c040778c849a),
    version(1.0)
]
library ConfigOPC
{
	importlib("stdole32.tlb");
    importlib("stdole2.tlb");


	//  Primary dispatch interface for CConfigOPCDoc
	
	[
        uuid(33146a05-b51c-4267-9864-c040778c849a)
    ]
	dispinterface IConfigOPC
	{
		properties:
			// NOTE - ClassWizard will maintain property information here.
			//    Use extreme caution when editing this section.
			//{{AFX_ODL_PROP(CConfigOPCDoc)
			//}}AFX_ODL_PROP
			
		methods:
			// NOTE - ClassWizard will maintain method information here.
			//    Use extreme caution when editing this section.
			//{{AFX_ODL_METHOD(CConfigOPCDoc)
			//}}AFX_ODL_METHOD

	};

	//  Class information for CConfigOPCDoc
	
	[ 
        uuid(33146a06-b51c-4267-9864-c040778c849a),
		helpstring("4CONTROL: Item configurator for OPC")
    ]
	coclass ConfigOPC
	{
		[default] dispinterface IConfigOPC;
		//interface ICompile;
        //interface ICEBackparse;
        //interface ICEAddonAction;
	};

	//{{AFX_APPEND_ODL}}
	//}}AFX_APPEND_ODL}}
};



