


// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "BPViewWrapper.h"

/////////////////////////////////////////////////////////////////////////////
// CBPViewWrapper

IMPLEMENT_DYNCREATE(CBPViewWrapper, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CBPViewWrapper properties

/////////////////////////////////////////////////////////////////////////////
// CBPViewWrapper operations

void CBPViewWrapper::AttachToBPMan(LPUNKNOWN pUnk)
{
	static BYTE parms[] =
		VTS_UNKNOWN;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pUnk);
}

void CBPViewWrapper::DetachFromBPMan()
{
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}