#if !defined(AFX_BPVIEWWRAPPER_H__2C4D71BE_208D_4062_BAC4_8311FD2477BA__INCLUDED_)
#define AFX_BPVIEWWRAPPER_H__2C4D71BE_208D_4062_BAC4_8311FD2477BA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000



// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CBreakPointView wrapper class

class CBPViewWrapper : public CWnd
{
protected:
	DECLARE_DYNCREATE(CBPViewWrapper)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
            = { 0x5ECE09E2, 0x3DBA, 0x419a, { 0xa6, 0x3d, 0xDC, 0xBD, 0x55, 0x7D, 0xDB, 0x4F } }; 
		//	= { 0xffaeb290, 0x716a, 0x11d2, { 0x8f, 0x5a, 0x0, 0x40, 0x5, 0x26, 0x50, 0x5b } };
        //5ECE09E2-3DBA-419a-A63D-DCBD557DDB4F
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void AttachToBPMan(LPUNKNOWN pUnk);
	void DetachFromBPMan();
};


#endif // !defined(AFX_BPVIEWWRAPPER_H__2C4D71BE_208D_4062_BAC4_8311FD2477BA__INCLUDED_)