#if !defined(AFX_POUVARSELCTRLWRAPPER_H__007FDB1E_B710_4A21_AA92_030EFA2D49E5__INCLUDED_)
#define AFX_POUVARSELCTRLWRAPPER_H__007FDB1E_B710_4A21_AA92_030EFA2D49E5__INCLUDED_

#include "PouVarSelection.h"

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPouVarSelCtrlWrapper wrapper class

class CPouVarSelCtrlWrapper : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPouVarSelCtrlWrapper)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7af62965, 0xdb27, 0x4ac9, { 0x83, 0x51, 0xd7, 0x1f, 0xa, 0x83, 0x96, 0x39 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	HRESULT ShowPouSelection();
	HRESULT ShowVarSelection(const CString& strPouName);
	HRESULT InitPouVarSelection();
    HRESULT SetVarSelectionHint(const CString& strPouName,
                                const CString& strVarNamePrefix,
                                const CString& strDataType);
    HRESULT LookupUserHelp(const CString& strPou,
                           CString& strFileName);
    HRESULT LookupHeader(const CString& strPou,
                         CString& strHeaderFile);
    HRESULT GetLRUPous(SAFEARRAY** parrPous);
    HRESULT GetPouXML(BSTR szPouName, 
                      BSTR* pszPouDef);
    HRESULT GetVarList(SAFEARRAY** parrVars);
    HRESULT GetPouList(SAFEARRAY** parrPous);
    HRESULT GetPouDefinition(BSTR szPouName, 
                             BSTR* pszPouDef);
    HRESULT GetPouMember(BSTR szPouName, 
                         SAFEARRAY** parrMembers);
    HRESULT ShowVarSelectionBox(LONG lXPos, LONG lYPos,
                                BSTR szLine, LONG lColumn,
                                BSTR szTypeHint,
                                BSTR szPouName,
                                BSTR* pszSelection,
                                LONG* plStartColumn,
                                LONG* plEndColumn);
    HRESULT DisablePouVarSelection(BOOL bDisable);

protected:
    CComQIPtr<IPouVarSelCtrl, &IID_IPouVarSelCtrl> m_pPouVarSel;
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_POUVARSELCTRLWRAPPER_H__007FDB1E_B710_4A21_AA92_030EFA2D49E5__INCLUDED_)
