//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CEMAIN.rc
//
#define IDR_MAINFRAME                   100
#define IDR_CEMAINTYPE                  101
#define IDR_CEMAINTYPE_CNTR_IP          102
#define IDR_IETOOLBAR                   103
#define IDR_DEBUGACCEL                  104
#define IDR_NAVACCEL                    105
#define IDR_WATCHACCEL                  106
#define IDR_VIEWTOOLBAR                 107
#define IDP_OLE_INIT_FAILED             108
#define IDP_FAILED_TO_CREATE            109
#define IDB_4CONTROL                    110
#define IDB_NAVIMAGELIST                111
#define IDB_TABIMAGELIST                112
#define IDB_WIZIMAGELIST                113
#define IDB_4CONTROLPRINT               114
#define IDI_ADDVAR                      115
#define IDI_REMOVEVAR                   116
#define IDI_REMOVEALL                   117
#define IDD_FINDFILE_DLG                118
#define IDD_CONNECT                     119
#define IDD_CONNECT_ERROR               120
#define IDD_ABOUTBOX                    121
#define IDD_NAVIGATOR                   122
#define IDD_FILE_STATUS                 123
#define IDD_MULTI_SELECT_DLG            124
#define IDD_SETTINGS_LIBRARY            125
#define IDD_SETTINGS_PASSWORD           126
#define IDD_SETTINGS_ENGINEERING        127
#define IDD_NEW_DLG                     128
#define FIF_POPUP_MENU                  129
#define IDR_HELPTOOLBAR                 130
#define IDD_PROJECT_SAVE_AS             131
#define IDD_PRINT_SETTINGS              133
#define IDD_COVER_PAGE_DATA             134
#define IDD_CHANGE_CAPTION              135
#define IDD_PRINT_HEADER                136
#define IDD_PRINT_FOOTER                137
#define IDB_CONTINUE                    138
#define IDD_PRINT_OPTIONS               139
#define IDB_STATEIMAGELIST              140
#define CG_ID_VIEW_NAVIGATOR            292
#define CG_ID_VIEW_WATCH                293
#define CG_ID_VIEW_MESSAGE              294
#define CG_ID_VIEW_POUVARSEL            295
#define CG_ID_VIEW_BPVIEW               296
#define CG_ID_VIEW_XREF                 297
#define CG_ID_VIEW_DEBUG                298
#define CG_ID_VIEW_LIB                  299
#define IDC_FILTER_NAME                 300
#define IDC_FILTER_CAT                  301
#define IDC_ClTREE                      302
#define IDC_FILTER_FRAME                303
#define IDC_FlTREE                      304
#define IDC_HWTREE                      305
#define IDC_TAB_NAVIGATOR               306
#define IDC_INSTTREE                    307
#define IDC_CONNECT_PROGRESS            308
#define IDC_CONNECT_STATE               309
#define IDC_FILE_PROP_NAME              310
#define IDC_LIB_PATH                    311
#define IDC_SET_PWD_READ                312
#define IDC_FILE_PROP_PATH              313
#define IDC_SET_PWD_FULL                314
#define IDC_FILE_PROP_SIZE              315
#define IDC_FILE_PROP_CREATED           316
#define IDC_FILE_PROP_LAST_MOD          317
#define IDC_FILE_PROP_READ_ONLY         318
#define IDC_MULTI_SEL_LIST              319
#define IDC_LIB_STANDARD_PATH           320
#define IDC_LIB_NAME                    321
#define IDC_NEW_BT_LIBRARY_PATH         322
#define IDC_LIB_TARGET                  323
#define IDC_SET_ENG_XREF                324
#define IDC_SET_ENG_VARSEL              325
#define IDC_SET_ENG_CONSOLE_INF         326
#define IDC_NEW_ST_FILE                 326
#define IDC_NEW_ED_FILE                 327
#define IDC_NEW_ST_PATH                 328
#define IDC_NEW_ED_PATH                 329
#define IDC_NEW_BT_PATH                 330
#define IDC_NEW_ST_GRP                  331
#define IDC_NEW_WIZLIST                 332
#define FIF_IDC_WHOLE_WORDS             333
#define FIF_IDC_REGULAR_EXP             334
#define FIF_IDC_CASE_SENSITIVE          335
#define FIF_IDC_FINDTEXT                336
#define FIF_IDC_INSERT_RE               337
#define IDC_PROJ_SAVE_AS_LOCATION       338
#define IDC_PROJ_SAVE_AS_NAME           339
#define IDC_PROJ_SAVE_AS_BROWSE         340
#define IDC_COVER_PAGE_CHECK            341
#define IDC_COVPAGE_BTN                 342
#define IDC_PS_FILE_VIEW_CHECK          343
#define IDC_HEADER_BTN                  344
#define IDC_CONTENTS_CHECK              345
#define IDC_FOOTER_BTN                  346
#define IDC_PS_CLASS_VIEW_CHECK         347
#define IDC_COVPAG_BITMAP_EDIT          348
#define IDC_PS_INST_VIEW_CHECK          348
#define IDC_COVPAG_BITMAP_SEL_BTN       349
#define IDC_PS_HW_VIEW_CHECK            349
#define IDC_COVPAG_PRJNAME_EDIT         350
#define IDC_PS_GRED_HEADER_CHECK        350
#define IDC_COVPAG_PRJNAMCAP_BTN        351
#define IDC_COVPAG_PRJNO_EDIT           352
#define IDC_CAPTION_EDIT                352
#define IDC_COVPAG_PRJNOCAP_BTN         353
#define IDC_COVPAG_PRJMAN_EDIT          354
#define IDC_COVPAG_PRJMANCAP_BTN        355
#define IDC_COVPAG_COMMENT_EDIT         356
#define IDC_COVPAG_COMMENTCAP_BTN       357
#define IDC_FOOTER_CBITMAP_SEL_BTN      359
#define IDC_FOOTER_REVNO1_EDIT          360
#define IDC_FOOTER_REVNO2_EDIT          361
#define IDC_FOOTER_REVNO3_EDIT          362
#define IDC_FOOTER_REVNO_BTN            364
#define IDC_FOOTER_CHDESCR1_EDIT        365
#define IDC_FOOTER_CHDESCR2_EDIT        366
#define IDC_FOOTER_CHDESCR3_EDIT        367
#define IDC_FOOTER_CBITMAP_EDIT         368
#define IDC_FOOTER_CHDESCR_BTN          369
#define IDC_FOOTER_CHDATE1_EDIT         370
#define IDC_FOOTER_CHDATE2_EDIT         371
#define IDC_FOOTER_CHDATE3_EDIT         372
#define IDC_FOOTER_CHDATE_BTN           374
#define IDC_FOOTER_CHNAME1_EDIT         375
#define IDC_FOOTER_CHNAME2_EDIT         376
#define IDC_FOOTER_CHNAME3_EDIT         377
#define IDC_FOOTER_CHNAME_BTN           379
#define IDC_FOOTER_DATE_EDIT            380
#define IDC_FOOTER_DRAWN_EDIT           381
#define IDC_FOOTER_APPROVED_EDIT        382
#define IDC_FOOTER_RELEASED_EDIT        383
#define IDC_FOOTER_DATE_BTN             384
#define IDC_FOOTER_DRAWN_BTN            385
#define IDC_FOOTER_APPR_BTN             386
#define IDC_FOOTER_REL_BTN              388
#define IDC_FOOTER_DATETIME_EDIT        389
#define IDC_FOOTER_INFO1_EDIT           390
#define IDC_FOOTER_INFO2_EDIT           391
#define IDC_FOOTER_PRJPATH_EDIT         395
#define IDC_FOOTER_OBJNAME_EDIT         397
#define IDC_FOOTER_INFO3_EDIT           398
#define IDC_FOOTER_PAGECNT_EDIT         399
#define IDC_FOOTER_INFO4_EDIT           400
#define IDC_PO_MODULE_COMBO             403
#define IDC_HEADER_LBITMAP_EDIT         404
#define IDC_CROSS_REF_CHECK             405
#define IDC_HEADER_LBITMAP_SEL_BTN      406
#define IDC_HEADER_RBITMAP_EDIT         407
#define IDC_HEADER_RBITMAP_SEL_BTN      408
#define IDC_HEADER_TITLE_EDIT           409
#define ID_INDICATOR_EDITPOS            800
#define ID_FILE_DELETE                  801
#define ID_SOFT_HOMEPAGE                802
#define ID_INDICATOR_MODE               803
#define ID_EDIT_ASSIGN                  804
#define ID_PROJECT_CLOSE                805
#define ID_FINDINFILES                  806
#define ID_VIEW_FULLSCREEN              807
#define ID_TOGGLE_NAVIGATOR             809
#define ID_TOGGLE_MSG_VIEW              810
#define ID_EXPAND_ALL                   811
#define ID_NAV_CUT                      812
#define ID_NAV_COPY                     813
#define ID_NAV_PASTE                    814
#define ID_COLLAPSE_ALL                 815
#define ID_TOGGLE_POU_SELECTION         816
#define ID_TOGGLE_WATCH_VIEW            817
#define ID_TOGGLE_BREAKPT_VIEW          818
#define ID_TOGGLE_LIB                   819
#define ID_UPDATE_MAIN_MENU             820
#define IDM_PROJECT_SAVE_AS             821
#define ID_TOGGLE_XREF                  822
#define ID_NAV_SHOW_NODE                823
#define ID_PLV_DELETE                   824
#define ID_BREAK                        825
#define ID_CLOSE_ALL_WINDOWS            826
#define IDM_NVCM_ADDIOVAR               830
#define IDM_CONTEXT_MENU                831
#define IDM_FILE_NEW                    832
#define IDM_FILE_OPEN                   833
#define IDM_FILE_CLOSE                  834
#define IDM_FILE_SAVE                   835
#define IDM_FILE_SAVE_AS                836
#define IDM_FILE_DELETE                 837
#define IDM_FILE_PRINT                  838
#define IDM_PROJECT_NEW                 839
#define IDM_PROJECT_OPEN                840
#define IDM_PROJECT_CLOSE               841
#define IDM_PROJECT_SAVE                842
#define IDM_PROJECT_DELETE              843
#define IDM_PROJECT_PRINT               844
#define IDM_PRJFILE_PRINT               845
#define IDM_DOCKING_VIEW                846
#define IDM_DEBUG_CONTEXT_MENU          847
#define IDM_NAV_CONTEXT_MENU            848
#define IDM_WATCH_CONTEXT_MENU          849
#define IDM_NAV_FV_OPEN_FILE            851
#define IDM_NAV_FV_CUT                  852
#define IDM_NAV_FV_COPY                 853
#define IDM_NAV_FV_PROPERTIES           854
#define FIF_IDM_ANY_CHAR                855
#define FIF_IDM_CHAR_IN_RANGE           856
#define FIF_IDM_CHAR_NOT_IN_RANGE       857
#define FIF_IDM_BEGIN_OF_LINE           858
#define FIF_IDM_END_OF_LINE             859
#define FIF_IDM_OR                      860
#define FIF_IDM_0_OR_MORE               861
#define FIF_IDM_1_OR_MORE               862
#define FIF_IDM_GROUP                   863
#define FIF_IDM_WHITESPACE              864
#define FIF_IDM_ALPHANUM_CHAR           865
#define FIF_IDM_ALPHABET_CHAR           866
#define FIF_IDM_DECIMAL_DIGIT           867
#define FIF_IDM_HEX_NUMBER              868
#define FIF_IDM_NUMBER                  869
#define FIF_IDM_INTEGER                 870
#define FIF_IDM_IDENTIFIER              871
#define FIF_IDM_ALPHABET_STRING         872
#define FIF_IDM_QUOTED_STRING           873
#define IDM_SAVE_ALL                    874
#define IDM_CONTINUE_TASK               875
#define ID_PRINT_SETTINGS               876
#define ID_TOOLS                        877
#define ID_FILE                         879
#define ID_NEXT_ERROR                   880
#define ID_PREVIOUS_ERROR               881
#define IDM_XREF_PRINT                  882
#define IDS_EDITPOS                     1400
#define IDS_PP_TARGETS                  1401
#define IDS_PP_CONTENTS                 1402
#define IDS_ERROR_CONNECT               1403
#define IDS_ERR_EXECUTE                 1404
#define IDS_ERROR_DISCONNECT            1405
#define IDS_ERROR_STARTRESOURCE         1406
#define IDS_ERROR_STOPRESOURCE          1407
#define IDS_ERROR_STARTTASK             1408
#define IDS_ERROR_STOPTASK              1409
#define IDS_ERROR_COLDSTART             1410
#define IDS_ERROR_WARMSTART             1411
#define IDS_COLDSTART                   1412
#define IDS_RESOURCECLEAR               1413
#define IDS_WARMSTART                   1414
#define IDS_STARTALLTASKS               1415
#define IDS_STOPALLTASKS                1416
#define IDS_ERROR_STARTALLTASKS         1417
#define IDS_ERROR_STOPALLTASKS          1418
#define IDS_ERROR_CLEAR                 1419
#define IDS_RUNCONTROL                  1420
#define IDS_STOPCONTROL                 1421
#define IDS_TOCS_EXCEPTION              1422
#define IDS_TOCS_TARG_CON_EX_ERR        1423
#define IDS_TOCS_TARG_CON_ERR           1424
#define IDS_TOCS_CSC_CON_EX_ERR         1425
#define IDS_TOCS_CSC_CON_ERR            1426
#define IDS_TOCS_NOT_CON                1427
#define IDS_TOCS_CON                    1428
#define IDS_TOCS_CON_EX                 1429
#define IDS_CSC_NOT_CON                 1430
#define IDS_CSC_WAIT_CON                1431
#define IDS_CSC_CON                     1432
#define IDS_CSC_INTERRUPTED             1433
#define IDS_CSC_WAIT_CON_EX             1434
#define IDS_CSC_CON_EX                  1435
#define IDS_CSC_SHUTDOWN                1436
#define IDS_RS_NOT_CON                  1437
#define IDS_RS_VERSION_CONFLICT         1438
#define IDS_RS_SERVICE_STOPPED          1439
#define IDS_RS_ERROR                    1440
#define IDS_RS_STOPPED                  1441
#define IDS_RS_RUNNING                  1442
#define IDS_FIF_MATCH                   1443
#define IDS_FIF_ABORT                   1444
#define IDS_USER_BREAKPOINT_REACHED     1445
#define IDS_TASK_STOPPED_NO_BPINFO      1446
#define IDS_USER_BREAKPOINT_NO_SOURCE   1447
#define IDS_TASK_STOPPED_NO_SOURCE      1448
#define IDS_CONNECT_ABORTED             1449
#define IDS_CONNECT_TIMEOUT             1450
#define IDS_CONNECT_INTERRUPT           1451
#define IDS_CONNECT_CONNECT             1452
#define IDS_CONNECT_TO_CONTROL          1453
#define IDS_REALLY_CLOSE_PROJECT        1454
#define IDS_GOTO_BREAKPOINT_NO_BPINFO   1455
#define IDS_GOTO_BREAKPOINT_NO_SOURCE   1456
#define IDS_ENABLEDEBUG                 1457
#define IDS_NO_COMPONENT                1458
#define IDS_NO_PART                     1459
#define IDS_STRING1460                  1460
#define IDS_FOLDER_EXISTING             1461
#define IDS_NEW_FOLDER                  1462
#define IDS_DATE_TIME_FORMAT            1463
#define IDS_NAV_FILEVIEW_TITLE          1464
#define IDS_NAV_CLASSVIEW_TITLE         1465
#define IDS_NAV_TARGETVIEW_TITLE        1466
#define IDS_NAV_INSTANCEVIEW_TITLE      1467
#define IDS_EXPAND_ALL                  1468
#define IDS_COLLAPSE_ALL                1469
#define IDS_COL_PRJLIST                 1470
#define IDS_DENY_DEBUG_WITHOUT_ASSIGN   1471
#define IDS_DENY_DEBUG_WITH_DUPLICATE_ASSIGN 1472
#define IDS_FILE_NOT_EXISTING           1473
#define IDS_CANNOT_OPEN_FILE            1474
#define IDS_FILE_ALREADY_IN_PROJECT     1475
#define IDS_FILE_NOT_COPIED             1476
#define IDS_TARGET_SELECTION            1477
#define IDS_FILE_REMOVED                1478
#define IDS_FV_DEL_FILE                 1479
#define IDS_FV_DEL_FILE_WARN            1480
#define IDS_FV_REFUSE_DEL_FILE          1481
#define IDS_FILE_EXISTING               1482
#define IDS_RENAME_FILE_WARN            1483
#define IDS_RENAME_FILE_DENIED          1484
#define IDS_FILE_OPEN_TITLE             1485
#define IDS_FILE_OPEN_FILTER            1486
#define IDS_PP_PROJECT                  1486
#define IDS_PLV_MENU_ITEM_DELETE        1487
#define IDS_FV_MENU_OPEN                1488
#define IDS_FV_MENU_CUT                 1489
#define IDS_FV_MENU_PROPERTIES          1490
#define IDS_FV_MENU_ADD_FILE            1491
#define IDS_FV_MENU_PASTE               1492
#define IDS_FV_MENU_DELETE              1493
#define IDS_FV_MENU_RENAME              1494
#define IDS_FV_MENU_CREATE_FOLDER       1495
#define IDS_PLV_MENU_GOTO_NAVIGATOR     1496
#define IDS_WARN_SAVE_INCOMPLETE        1497
#define IDS_NO_DDE_DURING_SHUTDOWN      1498
#define IDS_WARNING_ADDRESS_CHANGED     1499
#define IDS_ASK_DELETE_FILE_ERRNODE     1500
#define IDS_CANNOT_DELETE_ERRNODE       1501
#define IDS_ASK_DISCONNECT_TARGET       1502
#define IDS_REBUILD_HINT                1503
#define IDS_REALLY_DELETE_SEL_FILES     1504
#define IDS_PROJECT_IS_OPEN             1505
#define IDS_DL_ERROR                    1506
#define IDS_DL_ERROR_CONTINUE           1507
#define IDS_NO_DOWNLOAD_POSSIBLE        1508
#define IDS_DL_ERR_NO_CONN              1509
#define IDS_DL_ERR_NO_CONN_CONTINUE     1510
#define IDS_DL_ERR_DISCONN              1511
#define IDS_DL_ERR_DISCONN_CONTINUE     1512
#define IDS_DL_DISCONN_OLD              1513
#define IDS_ERROR_PRINT_FILE            1514
#define IDS_DEBUG_WITHOUT_PROJECT       1515
#define IDS_DEBUG_ON_DIFFERENT_PROJECT  1516
#define IDS_DEBUG_WITHOUT_BUILD         1517
#define IDS_DEBUG_UNKNOWN_DLSTATE       1518
#define IDS_VIEW_WATCH                  1519
#define IDS_VIEW_POUVARSEL              1520
#define IDS_VIEW_BREAKPOINT             1521
#define IDS_VIEW_XREF                   1522
#define IDS_4CCG_RUNNING                1523
#define IDS_LIB_PATH_NOT_FOUND          1524
#define IDS_FOOTER_PAGENUM              1525
#define IDS_FORMATVERSION_ERR           1526
#define IDS_SAVE_PROJECT_AS             1527
#define IDS_CLOSE_CURRENT_PROJECT       1528
#define IDS_WARNING_PROJ_EXISTS         1529
#define IDS_PROJ_SAVE_AS                1530
#define IDS_KAD_HELPER_FILTER_ALL       1531
#define IDS_KAD_HELPER_FILTER_SOURCE_FILES 1532
#define IDS_START_TASK                  1533
#define IDS_STOP_TASK                   1534
#define IDS_ADD_TAB_TOOLTIP             1535
#define IDS_LOAD_PROJECT_INIT           1536
#define IDS_LOAD_PROJECT_CONVERT        1537
#define IDS_LOAD_PROJECT_CONVERT_DONE   1538
#define IDS_LOAD_PROJECT_LOAD           1539
#define IDS_LOAD_PROJECT_LOAD_DONE      1540
#define IDS_STATUS_ADD_TARGET           1541
#define IDS_CHECKING_SOURCE_FILES       1542
#define IDS_CHECKING_HELP_FILES         1543
#define IDS_CHECKING_ADDITIONAL_FILES   1544
#define IDS_CHECKING_REST_FILES         1545
#define IDS_CHECKING_DONE               1546
#define IDS_STATUS_REMOVE_TARGET        1547
#define IDS_ADD_FILE_TITLE              1548
#define IDS_ALLFILTER                   1549
#define IDS_OVERWRITE_DOUBLE_FILES      1550
#define IDS_CAN_NOT_ADD_FILES           1551
#define IDS_COULD_NOT_COPY_FILES        1552
#define IDS_PROJ_SAVE_AS_FOLDER_EXISTS  1553
#define IDS_PROJ_SAVE_AS_CREATE_FOLDER_FAILED 1554
#define IDS_PROJ_SAVE_AS_RENAME_4CP     1555
#define IDS_PROJECT_SAVE_AS_RENAME_CON_FILE 1556
#define IDS_ERR_PROJECT_FILE_DROP       1557
#define IDS_WARN_DL_DURING_BPHOLD       1558
#define IDS_SOFING_HOMEADDR             1559
#define IDS_WARN_DISCONNECT_IN_BP       1560
#define IDS_CLASS                       1561
#define IDS_BUILD_PLV                   1562
#define IDS_DONE                        1563
#define IDS_SET_RWPWD_NO_RWPWD          1564
#define IDS_PAGE_NUM_INCORRECT          1565
#define IDS_ERR_NO_TARGET_TYPE          1566
#define IDS_COVPAG_PRJNAMCAP            1567
#define IDS_COVPAG_PRJNOCAP             1568
#define IDS_COVPAG_PRJMANCAP            1569
#define IDS_COVPAG_COMMENTCAP           1570
#define IDS_FOOTER_REVNOCAP             1571
#define IDS_FOOTER_REVCHDESCCAP         1572
#define IDS_FOOTER_REVDATECAP           1573
#define IDS_FOOTER_REVNAMECAP           1574
#define IDS_FOOTER_REVDRAWNCAP          1575
#define IDS_FOOTER_REVAPPRCAP           1576
#define IDS_FOOTER_REVRELCAP            1577
#define IDS_BMPFILTER                   1578
#define IDS_DATE_TIME_FORMAT_SHORT_ENG  1579
#define IDS_DATE_TIME_FORMAT_SHORT_GER  1580
#define IDS_PP_PAGE_COUNT               1581
#define IDS_PP_TREE_VIEWS               1582
#define IDS_PP_PAGE_NUMBER              1583
#define IDS_PP_COVERPAGE                1584
#define IDS_PP_FILE_VIEW                1585
#define IDS_PP_CLASS_VIEW               1586
#define IDS_PP_INST_VIEW                1587
#define IDS_PP_HW_VIEW                  1588
#define IDS_PRINT_FAILED                1589
#define IDS_PP_PROGRAM_NAME             1590
#define IDS_PP_COPYRIGHT                1591
#define IDS_DOWNLOAD_ERROR              1592
#define IDS_CANNOT_MOVE_NODE            1593
#define IDS_NO_PROJECT_OPEN             1594
#define IDS_PROJ_READ_ONLY              1595
#define IDS_TARGET_NOT_COMPILED         1596
#define IDS_DEBUG_WITHOUT_DOWNLOAD      1597
#define IDS_TARGET_NOT_COMPILED2        1598
#define IDS_READ_ONLY                   1599
#define IDS_LOAD_KAD_FAILED             1600
#define IDS_FV_MENU_CLOSE               1601
#define IDS_FV_MENU_OPEN_FILE           1602
#define IDS_FORCED_DEBUG_DISCONNECT     1603
#define IDS_NOT_COMPILED_WARNING        1604
#define IDS_ERROR_DOACTION              1605
#define IDS_PP_CROSS_REF                1606
#define IDS_CONNECTION_REQUIRED         1607
#define IDS_CONNECTION_EX_REQUIRED      1608
#define IDS_MAXDOCCOUNTREACHED          1609
#define ID_MAIN_MENU_BASE               1700
#define ID_MAIN_MENU_END                1899
#define ID_MAIN_TOOLBAR_BASE            1900
#define ID_MAIN_TOOLBAR_END             1920
#define IDS_TARGETTYPE_SELECTION        1921

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         883
#define _APS_NEXT_CONTROL_VALUE         410
#define _APS_NEXT_SYMED_VALUE           130
#endif
#endif
